require('core.packer')
require('core.keyboard')
require('core.telescope')
require('core.lsp')
require('core.lualine')
require('core.treesitter')
require('core.config')
require('core.nvimtree')
require('core.tabstop')

